defmodule MepagueoqueApi.Services.Turnstile do
  @moduledoc """
  Service for verifying Cloudflare Turnstile tokens.

  Turnstile is Cloudflare's CAPTCHA alternative that provides bot detection
  and verification for web applications. This service handles token verification
  by communicating with Cloudflare's API.

  ## Configuration

  Required environment variables:
    - TURNSTILE_SECRET_KEY: Your Cloudflare Turnstile secret key

  ## References
    - [Cloudflare Turnstile Documentation](https://developers.cloudflare.com/turnstile/)
  """

  require Logger

  @turnstile_url "https://challenges.cloudflare.com/turnstile/v0/siteverify"

  @type verification_response :: %{
          success: boolean(),
          challenge_ts: String.t() | nil,
          hostname: String.t() | nil,
          error_codes: [String.t()] | nil
        }

  @doc """
  Verifies a Turnstile token with Cloudflare's API.

  This function sends a verification request to Cloudflare's Turnstile API
  to validate that the token was generated by a legitimate user interaction.

  ## Parameters
    - token: The Turnstile response token received from the client
    - remoteip: (optional) The visitor's IP address for additional verification

  ## Returns
    - `{:ok, response}` if verification succeeds and token is valid
    - `{:error, reason}` if verification fails or token is invalid

  ## Examples

      iex> Turnstile.verify("valid_token_string", "192.168.1.1")
      {:ok, %{"success" => true, "hostname" => "example.com"}}

      iex> Turnstile.verify("invalid_token")
      {:error, "Turnstile verification failed"}

  ## Error Cases
    - Configuration missing: Secret key not set
    - Invalid token: Token failed verification
    - Network error: Unable to reach Cloudflare API
    - Service unavailable: Cloudflare API returned non-200 status
  """
  @spec verify(String.t(), String.t() | nil) :: {:ok, map()} | {:error, String.t()}
  def verify(token, remoteip \\ nil)

  def verify(token, remoteip) when is_binary(token) and token != "" do
    with {:ok, secret} <- get_secret_key(),
         {:ok, response} <- make_verification_request(secret, token, remoteip),
         {:ok, verified} <- validate_response(response) do
      {:ok, verified}
    end
  end

  def verify(_, _), do: {:error, "Invalid token format"}

  @spec get_secret_key() :: {:ok, String.t()} | {:error, String.t()}
  defp get_secret_key do
    case Application.get_env(:mepagueoque_api, :turnstile_secret) do
      nil ->
        Logger.error("Turnstile secret key is not configured")
        {:error, "Turnstile configuration missing"}

      "" ->
        Logger.error("Turnstile secret key is empty")
        {:error, "Turnstile configuration missing"}

      secret when is_binary(secret) ->
        {:ok, secret}
    end
  end

  @spec make_verification_request(String.t(), String.t(), String.t() | nil) ::
          {:ok, map()} | {:error, String.t()}
  defp make_verification_request(secret, token, remoteip) do
    params = %{secret: secret, response: token}

    params =
      if remoteip && is_binary(remoteip) && remoteip != "" do
        Map.put(params, :remoteip, remoteip)
      else
        params
      end

    case Req.post(@turnstile_url, form: params) do
      {:ok, %{status: 200, body: body}} when is_map(body) ->
        {:ok, body}

      {:ok, %{status: status, body: body}} ->
        Logger.error("Turnstile API returned status #{status}: #{inspect(body)}")
        {:error, "Turnstile service unavailable"}

      {:error, %{reason: reason}} ->
        Logger.error("Failed to verify Turnstile: #{inspect(reason)}")
        {:error, "Turnstile verification error"}

      {:error, reason} ->
        Logger.error("Failed to verify Turnstile: #{inspect(reason)}")
        {:error, "Turnstile verification error"}
    end
  end

  @spec validate_response(map()) :: {:ok, map()} | {:error, String.t()}
  defp validate_response(%{"success" => true} = body), do: {:ok, body}

  defp validate_response(%{"success" => false, "error-codes" => error_codes}) do
    Logger.warning("Turnstile rejected token. Codes: #{inspect(error_codes)}")
    {:error, format_error_codes(error_codes)}
  end

  defp validate_response(%{"success" => false}) do
    {:error, "Turnstile verification failed"}
  end

  defp validate_response(_body) do
    Logger.warning("Unexpected Turnstile response format")
    {:error, "Invalid response from Turnstile"}
  end

  @spec format_error_codes([String.t()]) :: String.t()
  defp format_error_codes(error_codes) when is_list(error_codes) do
    error_messages = %{
      "missing-input-secret" => "Configuração do servidor inválida",
      "invalid-input-secret" => "Configuração do servidor inválida",
      "missing-input-response" => "Token de verificação não fornecido",
      "invalid-input-response" => "Token inválido ou expirado. Por favor, tente novamente.",
      "timeout-or-duplicate" => "Token já foi usado. Por favor, recarregue a página.",
      "internal-error" => "Erro no serviço de verificação. Tente novamente."
    }

    # Map and join error messages
    messages =
      error_codes
      |> Enum.map(fn code -> Map.get(error_messages, code, code) end)
      |> Enum.uniq()

    # Return first message for better UX (avoid confusing multiple messages)
    List.first(messages) || "Verificação falhou"
  end

  defp format_error_codes(_), do: "Verificação falhou"
end
